### PR TITLE
Hook into keymapping

### LINKED ISSUE #11: which-key integration
Hi, (again,  I'm new to lua and vimscript,) I was wondering if there's any mechanism in which I could provide a mapping callback, or a delegate that would set the mapping instead?

### PR DESCRIPTION
**Pull request by Iron-E**
Closes #11. See the [docs](https://github.com/Iron-E/nvim-cartographer/blob/33247836ea5ec48f426d585e36bc8e8344174451/README.md#hooks)

### CODE REVIEW

**Comment by Esgariot** [comment]
Is `require 'cartographer'`-resolved table scoped to variable? Because running it like so:

```lua
local map1 = require 'cartographer'

map1:hook(function(buffer, modes, lhs, rhs, opts)
	print(vim.inspect(lhs)..'[map1] was mapped to '..vim.inspect(rhs))
end)


local map2 = require 'cartographer'

map2:hook(function(buffer, modes, lhs, rhs, opts)
	print(vim.inspect(lhs)..'[map2] was  mapped to '..vim.inspect(rhs))
end)

map1['zxpp'] = vim.lsp.buf.definition
map2['xxpp'] = vim.lsp.buf.definition

```

results in

```
"zxpp"[map2] was  mapped to '<Cmd>lua require("cartographer.callbacks")[3]()<CR>'                                                                                                                                            
"xxpp"[map2] was  mapped to '<Cmd>lua require("cartographer.callbacks")[4]()<CR>'     
```
(map2 in both calls)


This may be important, because for hook may depend on stuff that's outside of passed parameters, e.g. which-key allows setting group names for bindings, which would require different hooks per group or some logic in hooked function to determine group name.

...Let me also check whether it's just the case of "last `:hook` wins", in which case it all should be fine?

**Comment by Esgariot** [comment]
Yeah, calling it like so:

```lua
local map1 = require 'cartographer'

map1:hook(function(buffer, modes, lhs, rhs, opts)
	print(vim.inspect(lhs)..'[map1] was mapped to '..vim.inspect(rhs))
end)

map1['zxpp'] = vim.lsp.buf.definition

local map2 = require 'cartographer'

map2:hook(function(buffer, modes, lhs, rhs, opts)
	print(vim.inspect(lhs)..'[map2] was  mapped to '..vim.inspect(rhs))
end)

map2['xxpp'] = vim.lsp.buf.definition
```
works as expected:
```
"zxpp"[map1] was mapped to '<Cmd>lua require("cartographer.callbacks")[5]()<CR>'                                                                                                                                             
"xxpp"[map2] was  mapped to '<Cmd>lua require("cartographer.callbacks")[6]()<CR>'   
```

**Comment by Iron-E** [comment]
I see some weird behavior there— I would expect the following:

```lua
local map = require 'cartographer'
local map1 = map:hook(function(buffer, modes, lhs, rhs, opts) 	print(vim.inspect(lhs)..'[map1] was mapped to '..vim.inspect(rhs)) end)
local map2 = map:hook(function(buffer, modes, lhs, rhs, opts) 	print(vim.inspect(lhs)..'[map2] was mapped to '..vim.inspect(rhs)) end) 

map1['zxpp'] = vim.lsp.buf.definition
map2['xxpp'] = vim.lsp.buf.definition
```

This should yield:

```log
"zxpp"[map1] was mapped to '<Cmd>lua require("cartographer.callbacks")[3]()<CR>' "xxpp"[map2] was mapped to '<Cmd>lua require("cartographer.callbacks")[4]()<CR>' 
```

I'll look into why it isn't.

---

As for how it works, it is that each `hook` overrides the last. However, every time you `__index` the `cartographer` it copies itself. So if you do:

```lua
local map = require 'cartographer'
local map1 = map:hook(function(buffer, modes, lhs, rhs, opts) 	print(vim.inspect(lhs)..'[map1] was mapped to '..vim.inspect(rhs)) end)
local map2 = map1:hook(function(buffer, modes, lhs, rhs, opts) 	print(vim.inspect(lhs)..'[map2] was mapped to '..vim.inspect(rhs)) end) 
```

It should print the same as above. `map1` still has its hook, and `map2` has its hook. Though this PR may not reflect that behavior yet (I have to look into it, but that's the desired behavior)

With this plugin, you don't have to `require` multiple times per file due to how it makes a new copy of itself with every option you set.

**Comment by Iron-E** [comment]
@Esgariot you should try again now. I made some changes that may fix some of the issues you were having.

Also the `hook` doesn't require looping over the modes anymore.

**Comment by Esgariot** [comment]
I've adjusted my configs, `:WhichKey` picks up my keybindings, in buffer-specific and global contexts, as expected

<details>
<summary>callbacks.lua</summary>

```lua
local wk = require "which-key"

local function readonlytable(table)
   return setmetatable({}, {
     __index = table,
     __newindex = function(table, key, value)
                    error("Attempt to modify read-only table")
                  end,
     __metatable = false
   });
end

local callbacks = readonlytable {
  cartographer = function(buffer, mode, lhs, rhs, opts)
    local o = {}
    o["buffer"] = buffer
    o["mode"] = mode
    for k, v in pairs(opts) do
        o[k] = v
    end
    wk.register({[lhs] = {rhs}}, o)
    end

    }

return callbacks
```

</details>

```lua
-- global mapping

local map = require "cartographer"
local callbacks = require "user/callbacks"

map:hook(callbacks.cartographer)
map.i["jk"] = "<esc>"
```

```lua
-- buffer mapping, lsp

local lsp = require "lspconfig"
local callbacks = require "user/callbacks"

local function lsp_on_attach(client, buffer)
    local ml = map.nore["buffer" .. buffer]
    ml:hook(callbacks.cartographer)
    ml.n['<leader>?'] = '<cmd>lua vim.lsp.buf.hover()<CR>'
    ml.n['<leader>lf'] = '<cmd>lua vim.lsp.buf.formatting()<CR>'
end

lsp["sumneko_lua"].setup({ on_attach = lsp_on_attach })
```

That's the way I declare mappings, everything is working as expected

**Comment by Iron-E** [comment]
Great to hear! I will merge this.

**Pull request merged**
